name: Docker Image CI

on:
  push:
    branches: [ "ci/cd" ]
  pull_request:
    branches: [ "main" ]
  
  
  

jobs:
  django_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: build and test
        id: build_and_test
        env: 
          POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}

        run: docker compose -f docker-compose-test.yaml up --build --exit-code-from app_libary

      - name: docker login
        id: docker_login
        if: steps.build_and_test.outcome == 'success'
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKEHUB_USERNAME}}
          password: ${{secrets.DOCKEHUB_TOKEN}}

      - name: build and push image
        id: build_and_push
        if: steps.docker_login.outcome == 'success'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{secrets.DOCKEHUB_USERNAME}}/django_locallibary:latest
            ${{secrets.DOCKEHUB_USERNAME}}/django_locallibary:${{github.run_number}}

    # docker_test:

    #   runs-on: ubuntu-latest
    #   steps:
      
    #   - uses: actions/checkout@v4
      
    #   - name: run test
    #     run: docker compose up -d





        #   - name: Build the Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
